model_path: model/base_gpt2
lora_path: outputs/dpo_lora_output
dataset_path: data/processed/grpo_from_hh_soft.jsonl
output_dir: outputs/grpo_lora_output
logging_dir: logs/grpo
batch_size: 4
num_epochs: 3
max_seq_length: 512
